### ISSUE TITLE
Error when I run the Particular Platform Installer

### ISSUE THREAD

**Issue by donners77** [Particular/Workshop.Microservices#110]
Hi. When I go to https://particular.net/start-platform-download and run the installer I get an error message and a log file containing:

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 3 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 460805
Setting value '460805 {int}' for property 'DotNet45Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet45Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.5.2 (x86 and x64)':
Property: [DotNet45Full_OSIntegrated] = 1 {int}
Property: [DotNet45Full_Release] = 460805 {int}
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
Running checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet45Full_Release' and value '379893': true
Result of checks for command 'DotNetFX452\NDP452-KB2901954-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.5.2 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697208'
Error: An error occurred trying to download 'https://s3.amazonaws.com/particular.downloads/PlatformInstaller/PlatformInstaller.application'.

**Comment by donners77** [comment]
I'm having these problems on a azure vm created using the template: Visual Studio Enterprise 2017 (version 15.2) on Windows Server 2016 (x64)

**Comment by donners77** [comment]
I got this working in a Windows 10 virtual machine. Perhaps the problem is related to Windows Server 2016?

**Comment by adamralph** [comment]
@donners77 thanks for raising. I've not heard of problems with Windows Server 2016 specifically, but I'll investigate and let you know if I find anything out. In the meantime, it's good to know that you have this working in Windows 10. Is your Windows 10 VM also located in Azure or is it local?

**Comment by donners77** [comment]
Thanks. The Windows 10 VM is also located in Azure.

**Comment by donners77** [comment]
![azure vms](https://user-images.githubusercontent.com/5105950/29254011-fa3681f6-80ce-11e7-9b6d-0cdaa556800b.jpeg) The VM template which I installed and am having the problem in is the 3rd listed in this screenshot.

**Comment by HEskandari** [comment]
@donners77 Thanks for reporting it. I'll look into it (but most likely will be after the conference).

**Comment by donners77** [comment]
Sure

**Comment by mauroservienti** [comment]
If I remember correctly security is tighter on Windows Server compared to client versions, on 2016 ClickOnce ".application" apps are blocked by default and Windows Firewall doesn't allow them to be downloaded.
I do not remember the settings to tweak, but manually downloading the .application file and executing it should do the trick. That's one of the reasons Platform Installer is not supported on Windows Server.

**Comment by HEskandari** [comment]
@donners77 did you happen to run the installer on a different browser on Win 10 vs Win Server 2016? I have [another report](https://github.com/Particular/Workshop.Microservices/issues/112) that's very similar to yours.

**Comment by adamralph** [comment]
The pragmatic thing to do here is probably to change the workshop preparation instructions to specifically call out a Windows client edition as a prerequisite, rather than a server edition.

**Comment by donners77** [comment]
I tried using Edge, Chrome and Firefox on the Windows Server 2016 virtual machine. For all, the initial file downloaded ok but then ran into trouble once I executed it.  I can't remember which browser I used on the Windows 10 virtual machine but it was probably Chrome.

**Comment by adamralph** [comment]
Yep, the Windows Server problem is a separate problem from the browser.

As it stands:

- The installer does not work on Windows Server (regardless of which browser was used to download it). A Windows client edition must be used.
- The installer cannot be downloaded using Edge (regardless of which operating system is being used). Another browser should be used to download the installer (or perhaps some clever workaround).

**Comment by adamralph** [comment]
@donners77 thanks again for raising this. The instructions have been updated to [specify a Windows client edition](https://github.com/Particular/Workshop.Microservices#install-the-pre-requisites). I hope you enjoyed the workshop!
