### ISSUE TITLE
Error when I run Setup-Databases.ps1 script

### ISSUE THREAD

**Issue by donners77** [Particular/Workshop.Microservices#111]
Hi.

When I run Setup-Databases.ps1 within Visual Studio Code's Powershell Integrated Console I get the following:

PS C:\Users\cdonnelly> c:\Users\cdonnelly\Source\Repos\Workshop.Microservices\exercises\scripts\Setup-Databases.ps1

LocalDB instance "microservices-workshop" created with version 13.0.1601.5.
Private LocalDB instance "microservices-workshop" shared with the shared name: "microservices
-workshop".
LocalDB instance "microservices-workshop" started.
Name:               microservices-workshop
Version:            13.0.1601.5
Shared name:        microservices-workshop
Owner:              VmVs2017\cdonnelly
Auto-create:        No
State:              Running
Last start time:    8/13/2017 6:03:09 AM
Instance pipe name: np:\\.\pipe\LOCALDB#SHE63730\tsql\query
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Client unable to establish connection because an error was encountered during handshakes before login. Common c
causes include client attempting to connect to an unsupported version of SQL Server, server too busy to accept new connections or a resource limitation (memory or maxiu
mum allowed connections) on the server..
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Named Pipes Provider: No process is on the other end of the pipe.
.
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Client unable to establish connection.
Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Client unable to establish connection due to prelogin failure.

When I run it just in an elevated powershell prompt I get:
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\cdonnelly> C:\Users\cdonnelly\Source\Repos\Workshop.Microservices\exercises\scripts\Setup-Databases.ps1
LocalDB instance "microservices-workshop" created with version 13.0.1601.5.
Private LocalDB instance "microservices-workshop" shared with the shared name: "microservices-workshop".
LocalDB instance "microservices-workshop" started.
Name:               microservices-workshop
Version:            13.0.1601.5
Shared name:        microservices-workshop
Owner:              VmVs2017\cdonnelly
Auto-create:        No
State:              Running
Last start time:    8/13/2017 6:09:37 AM
Instance pipe name: np:\\.\pipe\LOCALDB#SHE63730\tsql\query
sqlcmd : The term 'sqlcmd' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\cdonnelly\Source\Repos\Workshop.Microservices\exercises\scripts\Setup-Databases.ps1:11 char:1
+ sqlcmd -S $serverName -i ".\Setup-Databases.sql"
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (sqlcmd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I'm having these problems on a azure vm created using the template: Visual Studio Enterprise 2017 (version 15.2) on Windows Server 2016 (x64)

**Comment by donners77** [comment]
Sorry. I missed the note in the instructions about if the setup script fails with a "sqllocaldb command not found" error.  

I installed the LocalDB stand alone package on my Windows 10 Visual Studio 2015 virtual machine and it is now working.

With my Windows Server 2016 Visual Studio 2017 virtual machine, it already has Microsoft SQL Server 2016 LocalDB installed on it.  Will installing the 2012 version as well cause problems?  Is there a way to get things working with the 2016 version?

**Comment by adamralph** [comment]
@donners77 on your Visual Studio 2017 machine, I recommend, running `Setup-Databases.ps1`. The script should succeed in creating the database instance, but then they will probably fail when trying to execute `Setup-Databases.sql`. As noted in the [set up instructions](https://github.com/Particular/Workshop.Microservices#when-using-localdb) (see the first "NOTE"), you can work around that problem by executing `Setup-Databases.sql` in Visual Studio.

**Comment by donners77** [comment]
Ok. Thanks.

**Comment by adamralph** [comment]
@donners77 assuming you managed to get everything running, I'll close this now. Please feel free to re-open if required.
