### ISSUE TITLE
Project Divergent.Sales.API.Host has an inconsistent default namespace and assembly name.

### ISSUE THREAD

**Issue by reashore** [Particular/Workshop.Microservices#136]
For the project Divergent.Sales.API.Host, the namespace and assembly name are not consistent with the project name.

The default namespace is Divergent.Shipping.API.Host and the assembly name is Divergent.Shipping.API.Host.

To verify this, right click on the project Divergent.Sales.API.Host and select Properties. Select the Application tab.

ReSharper verifies this inconsistency by underlining the namespaces with a blue squiggly line.

This should be an easy fix.

**Comment by mauroservienti** [comment]
@reashore thanks for reporting this, I raised https://github.com/Particular/Workshop.Microservices/pull/138 to fix.
