### ISSUE TITLE
BaseAddress is hard-coded

### ISSUE THREAD

**Issue by reashore** [Particular/Workshop.Microservices#144]
The base address is defined in the configuration files of the two "API.Host" projects.

However, it is hard-coded in the following files:
1) Divergent.Sales.ViewModelComposition.OrderDetailsViewModelAppender
2) Divergent.Shipping.ViewModelComposition.OrderDetailsViewModelAppender
3) Divergent.Sales.ViewModelComposition.OrdersListViewModelAppender

For example:

    string url = $"http://localhost:20296/api/shippinginfo/order/{id}";
	
So if the base address is changed then the application will fail.

**Comment by mauroservienti** [comment]
We had a discussion on https://github.com/Particular/Workshop.Microservices/pull/145 and concluded that it's not worth the effort right now, we'll reevaluate in the future.

**Comment by adamralph** [comment]
@reashore also note that we've now added explanatory comments, e.g. https://github.com/Particular/Workshop.Microservices/blob/d3d455ca04c725402f924cd8d306897a51dccf15/demos/asp-net-core/Divergent.Sales.ViewModelComposition/OrderDetailsViewModelAppender.cs#L24

Thanks for raising this.
