### ISSUE TITLE
Rename CompositionActionFilter to CompositionResultFilter 

### ISSUE THREAD

**Issue by reashore** [Particular/Workshop.Microservices#146]
CompositionActionFilter should be renamed to CompositionResultFilter since it derives from IAsyncResultFilter, and not IAsyncActionFilter.

Also the class is missing an explicit access modifier. Without an access modifier the access defaults to internal. Was the class intended to be public?

I noticed that many classes and methods in the solution lack explicit access modifiers. It is a best practice to provide explicit access modifiers. Note that ReSharper flags missing access modifiers.

**Comment by HEskandari** [comment]
@Particular/microservices-workshop-maintainers What's your thoughts on this?

**Comment by mauroservienti** [comment]
I have no opinions, I'd rather rename it to `CompositionFilter`, where it is positioned in the MVC pipeline should not be part of the name, especially since it's right now positioned as a result filter but might change in the future

**Comment by adamralph** [comment]
> I'd rather rename it to `CompositionFilter`

@mauroservienti I agree.

> Also the class is missing an explicit access modifier. Without an access modifier the access defaults to internal. Was the class intended to be public?

The lack of the modifier implies that the class is intended to be internal which, as you say, is the default.

> I noticed that many classes and methods in the solution lack explicit access modifiers. It is a best practice to provide explicit access modifiers.

@reashore this comes down to personal preference. Some teams prefer explicit. Some prefer implicit defaults. Personally, like you, I prefer explicit. However, if we want to change policy in this repo that's something to consider separately from this issue.

> Note that ReSharper flags missing access modifiers.

That depends on the ReSharper configuration. E.g. it can be configured to [flag redundant modifiers that repeat the default](https://github.com/Particular/NServiceBus.RabbitMQ/blob/d718c0373f7f680337238095d047060a46763cae/src/NServiceBus.Transport.RabbitMQ.sln.DotSettings#L142-L145).
