### ISSUE TITLE
Issue with database setup

### ISSUE THREAD

**Issue by pgorczynski** [Particular/Workshop.Microservices#151]
When I'm running Powershell script to setup database I get the following error:

> PS D:\git\Workshop.Microservices\exercises\scripts> .\Setup-Databases.ps1
LocalDB instance "microservices-workshop" created with version 13.0.2151.0.
Private LocalDB instance "microservices-workshop" shared with the shared name: "microservices-workshop".
LocalDB instance "microservices-workshop" started.
Name:               microservices-workshop
Version:            13.0.2151.0
Shared name:        microservices-workshop
Owner:              PRZEMEK-PC\Przemek
Auto-create:        No
State:              Running
Last start time:    2017-10-19 00:32:17
Instance pipe name: np:\\.\pipe\LOCALDB#SH87897A\tsql\query
HResult 0xFFFFFFFF, Level 16, State 1
SQL Server Network Interfaces: Error Locating Server/Instance Specified [xFFFFFFFF].
Sqlcmd: Error: Microsoft SQL Server Native Client 10.0 : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
Sqlcmd: Error: Microsoft SQL Server Native Client 10.0 : Login timeout expired.

When running Sql Managment Studio, I can connect to those two local servers:
- (LocalDb)\v11.0
- PRZEMEK-PC\SQLEXPRESS (here I run Setup-Databases.sql manually and it was successful, but it's not full instance, just express, so I understand that I should not use it)

**Comment by tmasternak** [comment]
Hi,

The instance that the `Setup-Databases.ps1` script should be run against is `(localdb)\microservices-workshop`. This is the instance that you will also find in the connections strings in the exercises.

Are you able to connect to `(localdb)\microservices-workshop` via. Sql Management Studio?

**Comment by adamralph** [comment]
@pgorczynski it's OK to use SQL Express if you prefer. Just follow the instructions at https://github.com/Particular/Workshop.Microservices#when-using-a-full-sql-server-instance.

In this context, "full" SQL Server instance include SQL Express. We mean "full" as in "not LocalDB".

**Comment by adamralph** [comment]
FYI raised https://github.com/Particular/Workshop.Microservices/pull/153 to clarify this.

**Comment by pgorczynski** [comment]
@tmasternak yes, I can connect to '(localdb)\microservices-workshop' via SSMS, but there is only one database 'Exercise-01-before-sales'. I run the 'Setup-Databases.sql' script manually and now I have all databases visible, so I think that I can use this database for tomorrow.

Thanks
