### ISSUE TITLE
Update console apps and web site projects to .NET Core

### ISSUE THREAD

**Issue by alexeyzimarev** [Particular/Workshop.Microservices#182]
Currently, all console service host apps and web site projects in excercises are using full .NET Framework. It should not be very hard to switch them to .NET Core.

**Comment by mauroservienti** [comment]
Hey @alexeyzimarev thanks for raising this. It’s in the plans, we’re simply waiting for NServiceBus on Net Core to be at least RC to migrate everything to .NET Core

**Comment by alexeyzimarev** [comment]
May be changing project file and adding `<Frameworks>net461</Frameworks>` to use full .NET Framework, would do for a moment?

**Comment by adamralph** [comment]
Is this also blocked while we want to keep supporting VS2015?

**Comment by alexeyzimarev** [comment]
Yeah, I am closing this one because of VS 2015.

**Comment by adamralph** [comment]
No problem @alexeyzimarev. At some point we will do this though, as soon as a) we decide to make VS 2017 the minimum requirement and b) NServiceBus 7 is in RC/RTM.
