### ISSUE TITLE
Verify that exercises work with VS 2017

### ISSUE THREAD

**Issue by udidahan** [Particular/Workshop.Microservices#51]
Now that VS 2017 has been released, we are likely to get attendees who have it installed, and possibly not having the older Visual Studios on their machine.

We should verify that all our exercises will still work.

**Comment by mauroservienti** [comment]
They do, already tested a couple of them randomly. The only issue is that, at least on my machine, when opening an exercise solution the startup projects are not preserved. I'll investigate if there is a better way to handle that.

**Comment by dvdstelt** [comment]
I just verified this and it works? Startup projects are preserved.

**Comment by mauroservienti** [comment]
Cool. Can we close this then @dvdstelt ?

**Comment by dvdstelt** [comment]
Verified it on a fresh clone, works like a charm. Unfortunately not the webpages for API projects. They just open up again.
