### ISSUE TITLE
Exercise 3 says it's configured to run as in-memory storage, but it's not

### ISSUE THREAD

**Issue by jbogard** [Particular/Workshop.Microservices#83]
See: https://github.com/Particular/Workshop.Microservices/blob/master/exercises/03%20-%20Sagas.md#exercise-32-add-state-to-the-saga

But: https://github.com/Particular/Workshop.Microservices/blob/master/exercises/src/03%20Sagas/before/Divergent.Shipping/Config/EndpointConfig.cs#L39

This causes the exercise to fail around creating the new boolean properties that are NOT marked as virtual from NHibernate configuration validation.

**Comment by adamralph** [comment]
Closed in #86
